title: YGC Guidelines
desc: YGC ITU guidelines and other useful documents and links

categories: /ygc/categories.yaml
# guidelines: /guidelines.csv
guidelines: https://docs.google.com/spreadsheets/d/14Hh92W1xii4c3awB_FFZzVHTeMrvutrudX3KViAe3io/export?format=csv

links:
  - title: Glan Clwyd ITU
    href: https://sites.google.com/view/glanclwydhospitalintensivecare/home
    icon: /assets/hospital-building.svg # https://icongr.am/material/hospital-building.svg?size=16&color=808080

  - title: UpToDate
    href: https://www.uptodate.com/contents/search
    icon: /assets/alpha-u-box.svg # https://icongr.am/material/alpha-u-box.svg?size=16&color=808080