title: YGC Guidelines
desc: YGC ITU guidelines and other useful documents and links

# categories: /ygc/categories.yaml
# guidelines: /ygc/guidelines.csv
categories: https://docs.google.com/spreadsheets/d/14Hh92W1xii4c3awB_FFZzVHTeMrvutrudX3KViAe3io/export?gid=599111487&format=csv
guidelines: https://docs.google.com/spreadsheets/d/14Hh92W1xii4c3awB_FFZzVHTeMrvutrudX3KViAe3io/export?format=csv
protected: https://script.google.com/macros/s/AKfycbyYH0dxXu1onI_wBxBuRsna_bjGLmwkhmEAH03DEMCUttEbL_0C/exec?t=auth

links:
  - title: Glan Clwyd ITU
    href: https://sites.google.com/view/glanclwydhospitalintensivecare/home
    icon: /assets/hospital-building.svg # https://icongr.am/material/hospital-building.svg?size=16&color=808080

  - title: UpToDate
    href: https://www.uptodate.com/contents/search
    icon: /assets/alpha-u-box.svg # https://icongr.am/material/alpha-u-box.svg?size=16&color=808080